package com.rpgdecorator.engine.combat;

import com.rpgdecorator.domain.Combatant;
import com.rpgdecorator.domain.DamageResult;
import com.rpgdecorator.domain.RandomSource;
import com.rpgdecorator.domain.Side;
import com.rpgdecorator.domain.TurnContext;
import com.rpgdecorator.domain.catalog.Ability;
import com.rpgdecorator.domain.catalog.Target;
import com.rpgdecorator.domain.decorator.Category;
import com.rpgdecorator.domain.effects.GuardDecorator;
import com.rpgdecorator.domain.event.CombatEvent;
import com.rpgdecorator.engine.combat.Combat.LoggedEvent;
import com.rpgdecorator.engine.effects.EffectManager;
import com.rpgdecorator.engine.effects.Layer;
import com.rpgdecorator.engine.effects.RemovalReason;
import java.util.List;

/** Client of the Decorator pattern: runs a full round (hero turn, then enemy turn) of design §5.3. */
public final class CombatEngine {

    private final EffectManager effectManager;
    private final DamageCalculator calculator;
    private final EnemyAI enemyAi;

    public CombatEngine(EffectManager effectManager, DamageCalculator calculator, EnemyAI enemyAi) {
        this.effectManager = effectManager;
        this.calculator = calculator;
        this.enemyAi = enemyAi;
    }

    /** Returns the events generated by this round, in order. */
    public List<LoggedEvent> executeRound(Combat combat, Action heroAction, RandomSource random) {
        TurnContext ctx = new TurnContextImpl(combat, random);
        validate(combat, heroAction, ctx);
        int firstNewEvent = combat.log().size();

        takeTurn(combat, Side.HERO, heroAction, ctx);
        if (!finishIfOver(combat, Side.HERO, ctx)) {
            takeTurn(combat, Side.ENEMY, enemyAi.decide(combat, random), ctx);
            if (!finishIfOver(combat, Side.ENEMY, ctx)) {
                combat.nextRound();
            }
        }
        return List.copyOf(combat.log().subList(firstNewEvent, combat.log().size()));
    }

    private void validate(Combat combat, Action action, TurnContext ctx) {
        if (combat.status() != CombatStatus.IN_PROGRESS) {
            throw new InvalidActionException(InvalidActionException.INVALID_STATE, "El combate ya terminó");
        }
        boolean canAct = combat.hero().canAct(ctx);
        if (action instanceof Action.Pass) {
            if (canAct) {
                throw new InvalidActionException(InvalidActionException.ACTION_NOT_ALLOWED,
                        "Solo puedes pasar el turno si no puedes actuar");
            }
            return;
        }
        if (!canAct) {
            throw new InvalidActionException(InvalidActionException.ACTION_NOT_ALLOWED,
                    "No puedes actuar este turno: solo puedes pasar");
        }
        if (action instanceof Action.UseAbility use) {
            Ability ability = combat.findAbility(Side.HERO, use.abilityId())
                    .orElseThrow(() -> new InvalidActionException(InvalidActionException.INVALID_VALUE,
                            "La habilidad no existe: " + use.abilityId()));
            int remaining = combat.cooldown(Side.HERO, ability.id());
            if (remaining > 0) {
                throw new InvalidActionException(InvalidActionException.ABILITY_ON_COOLDOWN,
                        ability.name() + " estará disponible en " + remaining + (remaining == 1 ? " turno" : " turnos"));
            }
        }
    }

    private void takeTurn(Combat combat, Side side, Action action, TurnContext ctx) {
        String actorId = combat.combatant(side).id();
        ctx.emit(new CombatEvent.TurnStarted(actorId));

        combat.combatant(side).onTurnStart(ctx);
        if (combat.combatant(side).currentHealth() == 0) {
            ctx.emit(new CombatEvent.Death(actorId));
            return;
        }

        if (!combat.combatant(side).canAct(ctx)) {
            ctx.emit(new CombatEvent.TurnSkipped(actorId, blockingEffectId(combat.combatant(side))));
        } else {
            resolve(combat, side, action, ctx);
        }

        combat.tickCooldowns(side);
        combat.update(effectManager.advanceTurn(combat.combatant(side), ctx));
        ctx.emit(new CombatEvent.TurnEnded(actorId));
    }

    private void resolve(Combat combat, Side side, Action action, TurnContext ctx) {
        Side rival = side == Side.HERO ? Side.ENEMY : Side.HERO;
        String actorId = combat.combatant(side).id();
        switch (action) {
            case Action.Attack attack -> {
                ctx.emit(new CombatEvent.ActionTaken(actorId, attack.type(), null));
                strike(combat, side, rival, 1.0, ctx);
            }
            case Action.Defend defend -> {
                ctx.emit(new CombatEvent.ActionTaken(actorId, defend.type(), null));
                combat.update(effectManager.apply(combat.combatant(side), GuardDecorator.ID, ctx, true));
            }
            case Action.UseAbility use -> {
                Ability ability = combat.findAbility(side, use.abilityId()).orElseThrow();
                ctx.emit(new CombatEvent.ActionTaken(actorId, use.type(), ability.id()));
                useAbility(combat, side, rival, ability, ctx);
                combat.startCooldown(side, ability);
            }
            case Action.Pass pass -> ctx.emit(new CombatEvent.ActionTaken(actorId, pass.type(), null));
        }
        announceDeath(combat, rival, ctx);
        announceDeath(combat, side, ctx);
    }

    // Design §4.7: self effects, then damage, then effects on the opponent (unless evaded), then purge.
    private void useAbility(Combat combat, Side side, Side rival, Ability ability, TurnContext ctx) {
        for (String effectId : ability.effectsOn(Target.SELF)) {
            combat.update(effectManager.apply(combat.combatant(side), effectId, ctx, true));
        }
        boolean landed = true;
        if (ability.attacks()) {
            landed = !strike(combat, side, rival, ability.damageMultiplier(), ctx).evaded();
        }
        if (combat.combatant(rival).currentHealth() == 0) {
            return;
        }
        if (landed) {
            for (String effectId : ability.effectsOn(Target.OPPONENT)) {
                combat.update(effectManager.apply(combat.combatant(rival), effectId, ctx, false));
            }
        }
        if (ability.purgesOpponent()) {
            combat.update(effectManager.purge(combat.combatant(rival), ctx));
        }
    }

    private DamageResult strike(Combat combat, Side side, Side rival, double multiplier, TurnContext ctx) {
        DamageResult result = calculator.attack(combat.combatant(side), combat.combatant(rival), multiplier, ctx);
        // A shield emptied by this hit leaves the chain right away instead of waiting for its owner's turn.
        combat.update(effectManager.remove(combat.combatant(rival),
                layer -> layer.shouldBeRemoved() && !layer.duration().isExpired(), RemovalReason.DEPLETED, ctx));
        return result;
    }

    private void announceDeath(Combat combat, Side side, TurnContext ctx) {
        Combatant combatant = combat.combatant(side);
        if (combatant.currentHealth() == 0) {
            ctx.emit(new CombatEvent.Death(combatant.id()));
        }
    }

    private boolean finishIfOver(Combat combat, Side justActed, TurnContext ctx) {
        Side rival = justActed == Side.HERO ? Side.ENEMY : Side.HERO;
        Side loser;
        if (combat.combatant(rival).currentHealth() == 0) {
            loser = rival;
        } else if (combat.combatant(justActed).currentHealth() == 0) {
            loser = justActed;
        } else {
            return false;
        }
        CombatStatus result = loser == Side.ENEMY ? CombatStatus.VICTORY : CombatStatus.DEFEAT;
        combat.finish(result);
        ctx.emit(new CombatEvent.CombatEnded(result.name()));
        return true;
    }

    private String blockingEffectId(Combatant outer) {
        return effectManager.layers(outer).stream()
                .filter(layer -> layer.category() == Category.CONTROL)
                .map(Layer::id)
                .findFirst()
                .orElse(null);
    }
}
